name: Dynamic Databricks Notebook Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      storageName:
        description: "Nombre del Storage"
        required: true
        default: "datalakefforeroprod03"

      catalog:
        description: "Catalogo"
        required: true
        default: "formula1_prod"

      credential:
        description: "Nombre de la credential"
        required: true
        default: "credential_formula1_prod"

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      # ============================================================
      # 1. CHECKOUT DEL REPOSITORIO
      # ============================================================

      - name: Checkout Repository
        uses: actions/checkout@v4


      # ============================================================
      # 2. INSTALAR jq Y curl
      # ============================================================

      - name: Install jq & curl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl


      # ============================================================
      # 3. EXPORTAR NOTEBOOKS DE PREPARACION DE AMBIENTE
      # ============================================================

      - name: Export multiple notebooks preparacion ambiente
        run: |

          ORIGIN_HOST=${{ secrets.DATABRICKS_ORIGIN_HOST }}
          ORIGIN_TOKEN=${{ secrets.DATABRICKS_ORIGIN_TOKEN }}

          NOTEBOOK_BASE="/Workspace/Users/fcamifox@gmail.com/proyecto_final_formula1/PrepAmb"

          NOTEBOOKS=(
            "01.Setup Project Environment"
            "02.Ayuda_Bronze"
            "03.Configuracion_Ambiente"
            "04.Ayuda_Silver"
            "test"
          )

          mkdir -p notebooks_to_deploy

          for nb in "${NOTEBOOKS[@]}"; do

            echo "=========================================="
            echo "Exportando: $nb"
            echo "=========================================="

            nb_encoded="${nb// /%20}"

            curl -f -s -X GET \
              -H "Authorization: Bearer $ORIGIN_TOKEN" \
              "$ORIGIN_HOST/api/2.0/workspace/export?path=$NOTEBOOK_BASE/$nb_encoded&format=DBC&direct_download=true" \
              --output "notebooks_to_deploy/$nb.dbc"

          done


      # ============================================================
      # 4. IMPORTAR NOTEBOOKS EN DESTINO
      # ============================================================

      - name: Deploy notebooks to Destination Workspace preparacion ambiente
        run: |

          DEST_HOST=${{ secrets.DATABRICKS_DEST_HOST }}
          DEST_TOKEN=${{ secrets.DATABRICKS_DEST_TOKEN }}

          DEST_BASE="/Workspace/Users/fcamifox@gmail.com/proyecto_final_formula1/PrepAmb"

          echo "Creando carpeta base:"
          echo "$DEST_BASE"

          curl -f -s -X POST \
            -H "Authorization: Bearer $DEST_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"path\":\"$DEST_BASE\"}" \
            "$DEST_HOST/api/2.0/workspace/mkdirs"


          for file in notebooks_to_deploy/*.dbc; do

            [ -e "$file" ] || continue

            name=$(basename "$file" .dbc)

            dest_path="$DEST_BASE/$name"

            echo "=========================================="
            echo "Importando:"
            echo "$file"
            echo "Destino:"
            echo "$dest_path"
            echo "=========================================="


            response=$(curl -f -s -X POST \
              -H "Authorization: Bearer $DEST_TOKEN" \
              -H "Content-Type: multipart/form-data" \
              -F "path=$dest_path" \
              -F "format=DBC" \
              -F "overwrite=true" \
              -F "content=@$file" \
              "$DEST_HOST/api/2.0/workspace/import")


            echo "Response:"
            echo "$response"

          done


      # ============================================================
      # 5. EXPORTAR NOTEBOOKS BRONZE
      # ============================================================

      - name: Export multiple notebooks bronze
        run: |

          ORIGIN_HOST=${{ secrets.DATABRICKS_ORIGIN_HOST }}
          ORIGIN_TOKEN=${{ secrets.DATABRICKS_ORIGIN_TOKEN }}

          NOTEBOOK_BASE="/Workspace/Users/fcamifox@gmail.com/proyecto_final_formula1/proceso/01-Bronze"

          NOTEBOOKS=(
            "01.Ingest Circuits File"
            "02.Ingest Races File"
            "03.Ingest Constructors File"
            "04.Ingest Drivers File"
            "05.Ingest Results File"
            "06.Ingest Sprints File"
          )

          rm -rf notebooks_to_deploy

          mkdir -p notebooks_to_deploy


          for nb in "${NOTEBOOKS[@]}"; do

            echo "=========================================="
            echo "Exportando: $nb"
            echo "=========================================="

            nb_encoded="${nb// /%20}"

            curl -f -s -X GET \
              -H "Authorization: Bearer $ORIGIN_TOKEN" \
              "$ORIGIN_HOST/api/2.0/workspace/export?path=$NOTEBOOK_BASE/$nb_encoded&format=DBC&direct_download=true" \
              --output "notebooks_to_deploy/$nb.dbc"

          done


      # ============================================================
      # 6. IMPORTAR NOTEBOOKS BRONZE EN DESTINO
      # ============================================================

      - name: Deploy notebooks to Destination Workspace bronze
        run: |

          DEST_HOST=${{ secrets.DATABRICKS_DEST_HOST }}
          DEST_TOKEN=${{ secrets.DATABRICKS_DEST_TOKEN }}

          DEST_BASE="/Workspace/Users/fcamifox@gmail.com/proyecto_final_formula1/proceso/01-Bronze"

          echo "Creando carpeta base:"
          echo "$DEST_BASE"


          curl -f -s -X POST \
            -H "Authorization: Bearer $DEST_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"path\":\"$DEST_BASE\"}" \
            "$DEST_HOST/api/2.0/workspace/mkdirs"


          for file in notebooks_to_deploy/*.dbc; do

            [ -e "$file" ] || continue

            name=$(basename "$file" .dbc)

            dest_path="$DEST_BASE/$name"


            echo "=========================================="
            echo "Importando:"
            echo "$file"
            echo "Destino:"
            echo "$dest_path"
            echo "=========================================="


            response=$(curl -f -s -X POST \
              -H "Authorization: Bearer $DEST_TOKEN" \
              -H "Content-Type: multipart/form-data" \
              -F "path=$dest_path" \
              -F "format=DBC" \
              -F "overwrite=true" \
              -F "content=@$file" \
              "$DEST_HOST/api/2.0/workspace/import")


            echo "Response:"
            echo "$response"

          done

          
      - name: Crear Catalogo Unity Catalog
          run: |
            export DATABRICKS_HOST="${{ secrets.DATABRICKS_DEST_HOST }}"
            export DATABRICKS_TOKEN="${{ secrets.DATABRICKS_DEST_TOKEN }}"

            STORAGE_NAME="datalakefforeroprod03"
            CATALOG="formula1_prod"

            echo "======================================"
            echo "Creando/verificando catalogo"
            echo "Catalogo: $CATALOG"
            echo "Storage : $STORAGE_NAME"
            echo "======================================"

            RESPONSE=$(curl -s -w "\n%{http_code}" \
              -X POST \
              -H "Authorization: Bearer $DATABRICKS_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{
                \"name\": \"$CATALOG\",
                \"catalog_type\": \"MANAGED_CATALOG\",
                \"storage_root\": \"abfss://metastore@${STORAGE_NAME}.dfs.core.windows.net/\",
                \"comment\": \"Catalogo para la arquitectura medallion del proyecto Formula1\"
              }" \
              "$DATABRICKS_HOST/api/2.1/unity-catalog/catalogs")

            BODY=$(echo "$RESPONSE" | sed '$d')
            HTTP_CODE=$(echo "$RESPONSE" | tail -n 1)

            echo "HTTP Code: $HTTP_CODE"
            echo "Respuesta:"
            echo "$BODY"

            if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
              echo "Catalogo creado correctamente."
            elif [ "$HTTP_CODE" = "400" ] && echo "$BODY" | grep -qi "already exists"; then
              echo "El catalogo ya existe. Continuando..."
            else
              echo "ERROR creando el catalogo."
              exit 1
            fi